[package]
name = "deer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "multipart"] }
image = "0.25.1"
bytes = "1.6.0"
dotenv = "0.15.0"
